groups:
- name: concourse
  jobs:
  - atc
  - blackbox
  - deploy
  - fly
  - baggageclaim
  - jettison
  - tsa
  - major
  - rc
  - shipit
  - testflight

- name: publish
  jobs:
  - aws-box
  - github-release
  - hangar
  - product
  - publish-houdini
  - push-departures
  - push-docs
  - virtualbox-box

- name: bosh-lite
  jobs: [provision]

- name: junk-drawer
  jobs: [master-merge]

jobs:
- name: fly
  public: true
  plan:
  - get: concourse
    trigger: true
  - aggregate:
    - task: linux
      file: concourse/ci/fly-linux.yml
    - task: darwin
      file: concourse/ci/fly-darwin.yml
    - task: windows
      file: concourse/ci/fly-windows.yml

- name: atc
  public: true
  plan:
  - get: concourse
    trigger: true
  - task: build
    file: concourse/ci/atc.yml

- name: baggageclaim
  public: true
  serial: true
  plan:
  - get: concourse
    trigger: true
  - task: build
    privileged: true
    file: concourse/ci/baggageclaim.yml

- name: blackbox
  public: true
  plan:
  - get: concourse
    trigger: true
  - task: build
    file: concourse/ci/blackbox.yml

- name: jettison
  public: true
  plan:
  - get: concourse
    trigger: true
  - task: build
    file: concourse/ci/jettison.yml

- name: tsa
  public: true
  plan:
  - get: concourse
    trigger: true
  - task: build
    file: concourse/ci/tsa.yml

- name: rc
  public: true
  plan:
  - get: concourse
    trigger: true
    passed: [atc, fly, blackbox, tsa, jettison, baggageclaim]
  - get: version
    trigger: true
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}

- name: major
  public: true
  plan:
  - get: version
    params: {bump: major}
  - put: version
    params: {file: version/number}

- name: provision
  serial: true
  plan:
  - aggregate:
    - get: deployments
    - get: bosh-lite
  - task: build
    privileged: true
    file: deployments/lite/ci/provision-bosh-lite.yml
  - conditions: [success, failure]
    put: deployments
    params: {repository: build/deployments, rebase: true}

- name: testflight
  public: true
  serial: true
  plan:
  - aggregate:
    - get: concourse
      trigger: true
      passed: [rc]
    - get: version
      trigger: true
      passed: [rc]
    - get: garden-linux-release
      trigger: true
      resource: garden-linux
    - get: lite-stemcell
  - task: build
    privileged: true
    file: concourse/ci/testflight.yml
    config: {params: {BOSH_LITE_IP: {{bosh-lite-ip}}}}

- name: deploy
  serial: true
  plan:
  - aggregate:
    - get: concourse
      trigger: true
      passed: [testflight]
      params: {fetch: [master]}
    - get: version
      trigger: true
      passed: [testflight]
    - get: garden-linux-release
      trigger: true
      passed: [testflight]
      resource: garden-linux
    - get: bosh-stemcell
      resource: aws-stemcell
    - get: deployments
      trigger: true
  - task: build-dev-release
    file: concourse/ci/deploy.yml
  - put: concourse-deployment
    params:
      manifest: deployments/ci/deployments/concourse.yml
      stemcells: [bosh-stemcell/*.tgz]
      releases:
        - garden-linux-release/*.tgz
        - build-dev-release/concourse/dev_releases/concourse/concourse-*.tgz
  - put: tracker
    params: {repos: [concourse]}

- name: shipit
  serial: true
  plan:
  - aggregate:
    - get: concourse
      passed: [deploy]
      params: {fetch: [master]}
    - get: version
      passed: [deploy]
      params: {bump: final}
    - get: garden-linux-release
      passed: [deploy]
      resource: garden-linux
    - get: deployments
  - task: create-final-release
    file: concourse/ci/shipit.yml
  - aggregate:
    - put: version
      params: {file: version/number}
    - put: concourse-master
      params:
        repository: create-final-release/concourse
        tag: version/number
        tag_prefix: v
    - put: final-release
      params: {from: create-final-release/concourse/releases/concourse/concourse-(.*).tgz}

- name: virtualbox-box
  public: true
  serial: true
  plan:
  - aggregate:
    - get: final-release
      trigger: true
      passed: [shipit]
    - get: garden-linux-release
      trigger: true
      passed: [shipit]
      resource: garden-linux
    - get: version
      trigger: true
      passed: [shipit]
    - get: concourse-lite
    - get: deployments
  - task: build-box
    privileged: true
    file: deployments/buildbox/ci/build-boxes.yml
  - put: virtualbox-box
    params: {from: build-box/concourse-lite/concourse-virtualbox-ubuntu-trusty-(.*).box}
  - get: concourse-develop
    params: {submodules: none}
  - task: build-release-notes
    file: concourse-develop/ci/build-release-notes.yml
    config:
      params:
        STRIP_HEADER: true
        VERSION_FILE: version/number
  - put: virtualbox-box-cloud
    params:
      description: build-release-notes/concourse-develop/notes.md
      release: true
      url: virtualbox-box/url
      version: virtualbox-box/version

- name: aws-box
  serial: true
  plan:
  - aggregate:
    - get: final-release
      trigger: true
      passed: [shipit]
    - get: garden-linux-release
      trigger: true
      passed: [shipit]
      resource: garden-linux
    - get: version
      trigger: true
      passed: [shipit]
    - get: concourse-lite
    - get: deployments
  - task: build-box
    privileged: true
    file: concourse-lite/ci/build-aws.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{aws-box-access-key}}
        AWS_SECRET_ACCESS_KEY: {{aws-box-secret-key}}
  - put: aws-box
    params: {from: build-box/concourse-lite/concourse-aws-ubuntu-trusty-(.*).box}
  - get: concourse-develop
    params: {submodules: none}
  - task: build-release-notes
    file: concourse-develop/ci/build-release-notes.yml
    config:
      params:
        STRIP_HEADER: true
        VERSION_FILE: version/number
  - put: aws-box-cloud
    params:
      description: build-release-notes/concourse-develop/notes.md
      release: true
      url: aws-box/url
      version: aws-box/version

- name: push-docs
  serial: true
  plan:
  - aggregate:
    - get: version
      trigger: true
      passed: [shipit]
    - get: concourse-develop
      params: {submodules: none}
  - task: build
    file: concourse-develop/ci/build-docs.yml
    config:
      params:
        ANALYTICS_ID: {{analytics-id}}
        VERSION_FILE: version/number
  - put: concourse-docs
    params:
      current_app_name: docs
      manifest: build/concourse-develop/docs/manifest.yml

- name: push-departures
  serial: true
  plan:
  - get: departures
    trigger: true
  - put: departures-app
    params:
      current_app_name: departures
      manifest: departures/manifest.yml

- name: github-release
  plan:
  - aggregate:
    - get: final-release
      trigger: true
      passed: [shipit]
    - get: garden-linux
      trigger: true
      passed: [shipit]
      resource: garden-linux
    - get: version
      trigger: true
      passed: [shipit]
    - get: concourse-develop
      params: {submodules: none}
  - aggregate:
    - task: build-docs
      file: concourse-develop/ci/build-release-notes.yml
      config:
        params:
          STRIP_HEADER: true
          VERSION_FILE: version/number
    - task: rename-release
      file: concourse-develop/ci/rename-release.yml
  - put: github-release
    params:
      name: build-docs/concourse-develop/release-name
      tag: build-docs/concourse-develop/release-name
      body: build-docs/concourse-develop/notes.md
      globs:
      - final-release/*.tgz
      - rename-release/garden-linux/garden-linux-*.tgz

- name: product
  serial: true
  plan:
  - aggregate:
    - get: p-concourse
      trigger: true
    - get: final-release
      trigger: true
      passed: [shipit]
    - get: garden-linux-release
      trigger: true
      passed: [shipit]
      resource: garden-linux
    - get: version
      trigger: true
      passed: [shipit]
    - get: vsphere-stemcell
  - task: build
    file: p-concourse/ci/build.yml
  - put: product
    params: {from: build/p-concourse/p-concourse-(.*).pivotal}

- name: hangar
  public: true
  plan:
  - get: hangar
    trigger: true
  - task: build
    file: hangar/build.yml

- name: publish-houdini
  plan:
  - get: houdini
    trigger: true
  - task: build-artifacts
    file: houdini/ci/build-artifacts.yml
  - put: houdini-artifacts
    params:
      name: build-artifacts/dist/release-name
      tag: build-artifacts/dist/release-name
      globs: [build-artifacts/dist/artifacts/*]

- name: master-merge
  plan:
    - aggregate:
      - get: concourse-master
        trigger: true
        params:
          fetch: [develop]
      - get: concourse # for build scripts
    - task: merge-to-develop
      file: concourse/ci/master-merge.yml
    - put: concourse
      params:
        repository: merge-to-develop/concourse-master

resources:
- name: version
  type: semver
  source:
    bucket: concourse-releases
    key: current-version
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: final-release
  type: s3
  source:
    bucket: concourse-releases
    regexp: concourse-(.*).tgz
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: virtualbox-box
  type: s3
  source:
    bucket: concourse-boxes
    regexp: concourse-virtualbox-ubuntu-trusty-(.*).box
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: aws-box
  type: s3
  source:
    bucket: concourse-boxes
    regexp: concourse-aws-ubuntu-trusty-(.*).box
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: concourse-deployment
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: {{bosh-deployment}}
    ignore_ssl: yes

- name: virtualbox-box-cloud
  type: vagrant-cloud
  source:
    username: concourse
    box: lite
    provider: virtualbox
    access_token: {{atlas-access-token}}

- name: aws-box-cloud
  type: vagrant-cloud
  source:
    username: concourse
    box: lite
    provider: aws
    access_token: {{atlas-access-token}}

- name: garden-linux
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/garden-linux-release

- name: tracker
  type: tracker
  source:
    tracker_url: https://www.pivotaltracker.com
    project_id: "1059262"
    token: {{tracker-token}}

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: vsphere-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

- name: lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

- name: concourse-lite
  type: git
  source:
    uri: https://github.com/concourse/concourse-lite.git
    branch: master

- name: concourse-develop
  type: git
  source:
    uri: https://github.com/concourse/concourse.git
    branch: develop

- name: concourse-docs
  type: cf
  source:
    api: {{cf-target}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}

- name: departures
  type: git
  source:
    uri: https://github.com/vito/departure-board.git
    branch: master

- name: departures-app
  type: cf
  source:
    api: {{cf-target}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}

- name: github-release
  type: github-release
  source:
    access_token: {{concourse-github-release-access-token}}
    repository: concourse
    user: concourse

- name: concourse
  type: git
  source:
    uri: git@github.com:concourse/concourse.git
    branch: develop
    private_key: {{concourse-repo-private-key}}

- name: concourse-master
  type: git
  source:
    uri: git@github.com:concourse/concourse.git
    branch: master
    private_key: {{concourse-repo-private-key}}

- name: bosh-lite
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-lite.git
    branch: master

- name: hangar
  type: git
  source:
    uri: https://github.com/concourse/hangar.git
    branch: master

- name: p-concourse
  type: git
  source:
    uri: https://github.com/concourse/p-concourse.git
    branch: master

- name: product
  type: s3
  source:
    bucket: concourse-product
    regexp: p-concourse-(.*).pivotal
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: deployments
  type: git
  source:
    uri: git@github.com:concourse/deployments.git
    branch: master
    private_key: {{deployments-repo-private-key}}

- name: houdini
  type: git
  source:
    uri: https://github.com/vito/houdini.git
    branch: master

- name: houdini-artifacts
  type: github-release
  source:
    user: vito
    repository: houdini
    access_token: {{houdini-github-release-access-token}}
