jobs:
- name: git-resource
  serial: true
  public: true
  plan:
  - get: git-resource
    trigger: true
  - put: resource-image
    resource: git-resource-image
    params: {build: git-resource}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: git-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

- name: docker-image-resource
  serial: true
  public: true
  plan:
  - get: docker-image-resource
    trigger: true
  - put: resource-image
    resource: docker-image-resource-image
    params: {build: docker-image-resource}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: docker-image-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

- name: time-resource
  serial: true
  public: true
  plan:
  - get: time-resource
    trigger: true
  - task: unit
    file: time-resource/build.yml
  - put: resource-image
    resource: time-resource-image
    params: {build: unit/gopath/src/github.com/concourse/time-resource}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: time-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

- name: archive-resource
  serial: true
  public: true
  plan:
  - get: archive-resource
    trigger: true
  - task: unit
    file: archive-resource/build.yml
  - put: resource-image
    resource: archive-resource-image
    params: {build: unit/build-root}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: archive-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

- name: bosh-deployment-resource
  serial: true
  public: true
  plan:
  - get: bosh-deployment-resource
    trigger: true
  - task: unit
    file: bosh-deployment-resource/build.yml
  - put: resource-image
    resource: bosh-deployment-resource-image
    params: {build: bosh-deployment-resource}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: bosh-deployment-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

- name: broker-resource
  serial: true
  plan:
  - get: broker-resource
    trigger: true
  - task: unit
    file: broker-resource/build.yml

- name: s3-resource
  serial: true
  plan:
  - get: s3-resource
    trigger: true
  - task: unit
    file: s3-resource/build.yml
    config:
      params:
        S3_TESTING_ACCESS_KEY_ID:  {{s3-resource-access-key}}
        S3_TESTING_SECRET_ACCESS_KEY: {{s3-resource-secret-key}}
        S3_TESTING_BUCKET: {{s3-resource-bucket}}
        S3_VERSIONED_TESTING_BUCKET: {{s3-resource-versioned-bucket}}
        S3_TESTING_REGION: {{s3-resource-region}}
  - put: resource-image
    resource: s3-resource-image
    params: {build: unit/gopath/src/github.com/concourse/s3-resource}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: s3-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

- name: github-release-resource
  serial: true
  public: true
  plan:
  - get: github-release-resource
    trigger: true
  - task: unit
    file: github-release-resource/build.yml
  - put: resource-image
    resource: github-release-resource-image
    params: {build: unit/gopath/src/github.com/concourse/github-release-resource}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: github-release-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

- name: cf-resource
  serial: true
  public: true
  plan:
  - aggregate:
    - get: cf-resource
      trigger: true
    - get: cf-cli
      trigger: true
    - get: autopilot
      trigger: true
  - aggregate:
    - task: autopilot-unit
      file: autopilot/build.yml
    - task: resource-unit
      file: cf-resource/build.yml
  - put: resource-image
    resource: cf-resource-image
    params: {build: resource-unit/gopath/src/github.com/concourse/cf-resource}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: cf-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

- name: semver-resource
  serial: true
  public: false # easy to leak bucket params
  plan:
  - get: semver-resource
    trigger: true
  - task: unit
    file: semver-resource/build.yml
    config:
      params:
        SEMVER_TESTING_ACCESS_KEY_ID: {{semver-access-key}}
        SEMVER_TESTING_SECRET_ACCESS_KEY: {{semver-secret-key}}
        SEMVER_TESTING_BUCKET: {{semver-bucket}}
        SEMVER_TESTING_REGION: {{semver-region}}
  - put: resource-image
    resource: semver-resource-image
    params: {build: unit/gopath/src/github.com/concourse/semver-resource}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: semver-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

- name: bosh-io-release-resource
  serial: true
  public: true
  plan:
  - get: bosh-io-release-resource
    trigger: true
  - put: resource-image
    resource: bosh-io-release-resource-image
    params: {build: bosh-io-release-resource}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: bosh-io-release-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

- name: bosh-io-stemcell-resource
  serial: true
  public: true
  plan:
  - get: bosh-io-stemcell-resource
    trigger: true
  - put: resource-image
    resource: bosh-io-stemcell-resource-image
    params: {build: bosh-io-stemcell-resource}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: bosh-io-stemcell-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

- name: tracker-resource
  serial: true
  public: true
  plan:
  - get: tracker-resource
    trigger: true
  - task: unit
    file: tracker-resource/build.yml
  - put: resource-image
    resource: tracker-resource-image
    params: {build: unit/build-root}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: tracker-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

- name: vagrant-cloud-resource
  serial: true
  public: true
  plan:
  - get: vagrant-cloud-resource
    trigger: true
  - resource: resource-image
    put: vagrant-cloud-resource-image
    params: {build: vagrant-cloud-resource}
    get_params: {rootfs: true}
  - aggregate:
    - get: deployments
    - get: concourse
  - task: bump-package
    file: concourse/ci/bump-resource-package.yml
    config: {params: {RESOURCE_NAME: vagrant-cloud-resource}}
  - put: concourse
    params: {repository: bump-package/concourse, rebase: true}

resources:
- name: git-resource
  type: git
  source:
    uri: https://github.com/concourse/git-resource.git
    branch: master

- name: docker-image-resource
  type: git
  source:
    uri: https://github.com/concourse/docker-image-resource.git
    branch: master

- name: time-resource
  type: git
  source:
    uri: https://github.com/concourse/time-resource.git
    branch: master

- name: tracker-resource
  type: git
  source:
    uri: https://github.com/concourse/tracker-resource.git
    branch: master

- name: vagrant-cloud-resource
  type: git
  source:
    uri: https://github.com/concourse/vagrant-cloud-resource.git
    branch: master

- name: cf-resource
  type: git
  source:
    uri: https://github.com/concourse/cf-resource.git
    branch: master

- name: broker-resource
  type: git
  source:
    uri: https://github.com/concourse/broker-resource.git
    branch: master

- name: s3-resource
  type: git
  source:
    uri: https://github.com/concourse/s3-resource.git
    branch: master

- name: github-release-resource
  type: git
  source:
    uri: https://github.com/concourse/github-release-resource.git
    branch: master

- name: semver-resource
  type: git
  source:
    uri: https://github.com/concourse/semver-resource.git
    branch: master

- name: archive-resource
  type: git
  source:
    uri: https://github.com/concourse/archive-resource.git
    branch: master

- name: bosh-deployment-resource
  type: git
  source:
    uri: https://github.com/concourse/bosh-deployment-resource.git
    branch: master

- name: bosh-io-release-resource
  type: git
  source:
    uri: https://github.com/concourse/bosh-io-release-resource.git
    branch: master
    ignore_paths: [README.md]

- name: bosh-io-stemcell-resource
  type: git
  source:
    uri: https://github.com/concourse/bosh-io-stemcell-resource.git
    branch: master
    ignore_paths: [README.md]

- name: git-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/git-resource

- name: docker-image-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/docker-image-resource

- name: archive-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/archive-resource

- name: bosh-deployment-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/bosh-deployment-resource

- name: time-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/time-resource

- name: tracker-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/tracker-resource

- name: vagrant-cloud-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/vagrant-cloud-resource

- name: cf-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/cf-resource

- name: s3-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/s3-resource

- name: github-release-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/github-release-resource

- name: semver-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/semver-resource

- name: bosh-io-release-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/bosh-io-release-resource

- name: bosh-io-stemcell-resource-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: concourse/bosh-io-stemcell-resource

- name: autopilot
  type: git
  source:
    uri: https://github.com/concourse/autopilot.git
    branch: master

- name: cf-cli
  type: s3
  source:
    bucket: go-cli
    regexp: releases/v(.*)/cf-linux-amd64.tgz

- name: concourse
  type: git
  source:
    uri: git@github.com:concourse/concourse.git
    branch: develop
    private_key: {{concourse-repo-private-key}}

- name: deployments
  type: git
  source:
    uri: git@github.com:concourse/deployments.git
    branch: master
    private_key: {{deployments-repo-private-key}}

